quarkus.langchain4j.skills.directories=.agents/skills

quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
#quarkus.langchain4j.openai.base-url=http://127.0.0.1:11434

#quarkus.langchain4j.chat-model.provider=ollama
#quarkus.langchain4j.ollama.chat-model.model-name=nemotron-cascade-2
#quarkus.langchain4j.ollama.base-url=http://127.0.0.1:11434

# Increase timeout for tool execution (in seconds)
quarkus.langchain4j.openai.timeout=60s
quarkus.langchain4j.ollama.timeout=60s
